# "scss-lintルール設定"
# https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md
# "scss lintルールの日本語訳"
# https://github.com/makotot/scss-lint-example
linters:

  # !の前に不適切なスペースがある時に警告
  BangFormat:
    space_before_bang: true
    space_after_bang: false

  # border: noneを使う
  BorderZero:
    enabled: true
    convention: none

  # 16進カラーコードを使うようにする
  ColorKeyword:
    enabled: true

  # 色の指定は変数以外でもできる
  ColorVariable:
    enabled: false

  # 複数のクラスを重ねて指定しない
  ChainedClasses:
    enabled: true

  # コメントで//を使う
  Comment:
    enabled: true
    style: silent

  # @debugが残っていないか
  DebugStatement:
    enabled: true

  # そのクラスに対するスタイルの設定は先頭に書く
  DeclarationOrder:
    enabled: true

  # リントで引っかかった理由を表示するか（？）
  DisableLinterReason:
    enabled: false

  # プロパティのダブりを許容しない
  DuplicateProperty:
    enabled: true

  # @elseの前後の波括弧で改行しない
  ElsePlacement:
    enabled: true
    style: same_line

  # ブロックの間に改行を入れる
  EmptyLineBetweenBlocks:
    enabled: true
    ignore_single_line_blocks: true

  # 空のスタイル設定を許容しない
  EmptyRule:
    enabled: true

  # ファイルの最後の行は空行じゃなくてもいい
  FinalNewline:
    enabled: false

  # カラーコードは常に6桁で記述
  HexLength:
    enabled: true
    style: long

  # 色コードは小文字で記述
  HexNotation:
    enabled: true
    style: lowercase

  # カラーコードが適切な長さかチェック
  HexValidation:
    enabled: true

  # IDを許容しない
  IdSelector:
    enabled: true

  # !importantを許容しない
  ImportantRule:
    enabled: true

  # @importを使用するとき、
  #   _はじまりを許容しない
  #   拡張子を許容しない
  ImportPath:
    leading_underscore: false
    filename_extension: false

  # インデントは4スペースにする
  Indentation:
    enabled: true
    character: space
    width: 4

  # 0始まりの小数点の値は0を省略しない
  LeadingZero:
    enabled: true
    style: include_zero

  # セレクタの重複をチェック。ネスト可能であれば必ずネスト。
  MergeableSelector:
    enabled: true
    force_nesting: true

  # 関数、ミックスイン、変数のフォーマットは小文字のハイフンつなぎにする
  NameFormat:
    enabled: true
    convention: hyphenated_lowercase

  # ネストの深さを６階層まで許容
  NestingDepth:
    enabled: true
    max_depth: 6
    ignore_parent_selectors: false
    enabled: true

  # @extendのセレクタは常にプレースホルダー以外も使える
  PlaceholderInExtend:
    enabled: false

  # プロパティの順序チェックはsmacss方式で（https://github.com/brigade/scss-lint/blob/master/data/property-sort-orders/smacss.txt）
  PropertySortOrder:
    order: smacss

  # 存在しないプロパティを使用していたらチェック
  PropertySpelling:
    enabled: true
    extra_properties: []

  # 擬似要素はダブルコロンで記述
  PseudoElement:
    enabled: true

  # タグと、クラス、ID、属性の組み合わせによるセレクターを記述しない
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: false
    allow_element_with_class: false
    allow_element_with_id: false

  # セレクタの深さを設定
  SelectorDepth:
    enabled: true
    max_depth: 6

  # セレクタの命名をチェックしない
  SelectorFormat:
    enabled: false

  # １行につき１つのプロパティにする。
  SingleLinePerProperty:
    enabled: true
    allow_single_line_rule_sets: false

  # １行につき１つのセレクタにする
  SingleLinePerSelector:
    enabled: true

  # カンマの後にスペースを入れるか
  SpaceAfterComma:
    enabled: true

  # プロパティのコロンの後にスペースを入れる
  SpaceAfterPropertyColon:
    enabled: true

  # プロパティの名前の後にスペースを入れる
  SpaceAfterPropertyName:
    enabled: true

  # 波括弧の前にスペースを入れる
  SpaceBeforeBrace:
    enabled: false

  # 丸括弧の前後にスペースを入れない
  SpaceBetweenParens:
    enabled: true
    spaces: 0

  # クオートの種類指定
  StringQuotes:
    enabled: true
    style: double_quotes

  # プロパティーの値の後にセミコロンを入れるか
  TrailingSemicolonAfterPropertyValue:
    enabled: true

  # 余計な空白を警告
  TrailingWhitespace:
    enabled: true

  # 小数点以下に不要な０を入れない
  TrailingZero:
    enabled: true

  # 不必要な小数点をつけない
  UnnecessaryMantissa:
    enabled: true

  # 親要素の参照が不要なときに&を使わない
  UnnecessaryParentReference:
    enabled: true

  # urlにプロトコルやドメインを含めない
  UrlFormat:
    enabled: true

  # URLをクオートで囲む
  UrlQuotes:
    enabled: true

  # ベンダープレフィックスを記述しない
  VendorPrefix:
    enabled: true

  # 0に単位をつけない（0pxと記述しない）
  ZeroUnit:
    enabled: true